trigger:
- main  # Trigger on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Azure-hosted agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Installing dependencies"
    pip install -r requirements.txt
  displayName: "Install Dependencies"

- script: |
    echo "Running tests"
    pytest
  displayName: "Run Tests"

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'cryptovisionops'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
